Severity Code Description Project File Line Suppression State Error CS0103 The name 'picker' does not exist in the current context Project-K C:\Users\karli\source\repos\Project-K\Project-K\Project-K\Views\UcitelPickerPage.xaml.cs 28 Active
Severity Code Description Project File Line Suppression State
Error  'Clicked' is an unexpected token. Expecting white space. Line 49, position 33. Project-K C:\Users\karli\source\repos\Project-K\Project-K\Project-K\Views\UcitelPickerPage.xaml 49